services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-apache
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
      - ./generations/third/newmr-theme:/var/www/html/wp-content/themes/newmr-theme
      - ./generations/third/newmr-plugin:/var/www/html/wp-content/plugins/newmr-plugin

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      DONATE_BOX_HTML: '<a href="https://newmr.org/support-newmr/"><img data-recalc-dims="1" decoding="async" src="https://i0.wp.com/newmr.org/wp-content/uploads/sites/2/2025/01/Support-us-Please.png?ssl=1" alt="“NewMR" patrons”=""></a>'
      ABOUT_BOX_HTML: '<h3>About NewMR</h3><p>NewMR organises online events, this website &amp; the LinkedIn NewMR group. NewMR is owned and operated by The Future Place and managed by Ray Poynter.</p><p> NewMR partners with <a href="https://researchwiseai.com"> ResearchWiseAI</a> to provide training courses and a range of AI-assisted tools.</p><p>To read our Data Privacy and GDPR statement, <a href="https://newmr.org/gdpr/">click here</a>. Keep in touch by <a href="http://eepurl.com/hAnKA">signing up to our mailings</a>. NewMR.org is funded by donations &amp; sponsorship.</p><p>Our sponsors are: Hello Ara, Platform One, Fuel, Indiefield, Enghouse, Infotools, QuestionPro, YouScan, Yasna.</p>'
      GA_CODE: 'GT-M3VRRZ2'
      LEFT_PAGE_SLUG: gdpr
      RIGHT_PAGE_SLUG: gdpr
      FEATURED_VIDEO_SLUG: 387df3a0
    working_dir: /var/www/html
    volumes:
      - wp_data:/var/www/html
      - ./generations/third/newmr-theme:/var/www/html/wp-content/themes/newmr-theme
      - ./generations/third/newmr-plugin:/var/www/html/wp-content/plugins/newmr-plugin
      - ./scripts:/var/www/html/scripts

  assets:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: >-
      sh -c "npm install --prefix generations/third/newmr-theme && \
      npm run --prefix generations/third/newmr-theme watch"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      WP_DB_HOST: db
      WP_DB_USER: wordpress
      WP_DB_PASS: wordpress
      WP_DB_NAME: wordpress
    volumes:
      - ./:/app
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    ports:
      - "8080:80"

volumes:
  db_data:
  wp_data:
