services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-apache
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
      - ./generations/third/newmr-theme:/var/www/html/wp-content/themes/newmr-theme
      - ./generations/third/newmr-plugin:/var/www/html/wp-content/plugins/newmr-plugin

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
      - ./generations/third/newmr-theme:/var/www/html/wp-content/themes/newmr-theme
      - ./generations/third/newmr-plugin:/var/www/html/wp-content/plugins/newmr-plugin

  assets:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: >-
      sh -c "npm install --prefix generations/third/newmr-theme && \
      npm run --prefix generations/third/newmr-theme watch"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      WP_DB_HOST: db
      WP_DB_USER: wordpress
      WP_DB_PASS: wordpress
      WP_DB_NAME: wordpress
    volumes:
      - ./:/app
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    ports:
      - "8080:80"

volumes:
  db_data:
  wp_data:
